### ISSUE TITLE
Missing section in the docs

### ISSUE THREAD

**Issue by TAKANOME-DEV** [taskless/taskless#16]
In the `@taskless/dev` docs, there is a missing section explaining what this package is for.

| ![docs_1](https://user-images.githubusercontent.com/79809121/195451346-51e127c7-efd2-4285-b5b6-fbd5c1423e19.png)	| ![docs_2](https://user-images.githubusercontent.com/79809121/195451378-56127982-3388-4a0e-a034-0bd2667a9154.png)  	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                      	|                                                                                                                       	|

**Comment by jakobo** [comment]
I'll go digging in git history. Maybe it went missing while we were migrating to the new markdoc infrastructure.

**Comment by jakobo** [comment]
Solved. Found what it was supposed to say and it was lost while copy-pasting markdoc stuff. Thanks for catching it!
