### ISSUE TITLE
Feature: fixed the position of the sidebar on the docs

### ISSUE THREAD

**Issue by TAKANOME-DEV** [taskless/taskless#2]
After taking a tour at [taskless/docs](https://taskless.io/docs/packages/express), I noticed that when you scroll, the sidebar scroll as well.
I think it should be great if the position is fixed, just to facilitate the navigation and jumps between sections.

**Comment by jakobo** [comment]
That would be pretty awesome. We're using tailwind.css under the hood for the docs page, so now might be a good time to give that `sticky` class a try. :)

**Comment by TAKANOME-DEV** [comment]
Yeah for sure, I'll work on it ASAP

**Comment by TAKANOME-DEV** [comment]
There are some typos that my extension [spell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) is highlighting.
Example: 
  - `maintaing` in `/docs/readme`
  - `intergations` in `/docs/packages/client`
  - `convienence`  in `/docs/packages/express and next`
  - `rexported` in `/docs/packages/express and next`
  - `wraped` in `/docs/packages/next`
  - etc

**Comment by jakobo** [comment]
> There are some typos that my extension [spell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) is highlighting. 

TIL there's an excellent spell checker built in to vscode!

**Comment by TAKANOME-DEV** [comment]
Should I only fix the sidebar or can I also fix theses typos ??

**Comment by TAKANOME-DEV** [comment]
And also  I'm struggling to find the sidebar section :sweat_smile: can you help me??

**Comment by jakobo** [comment]
The actual HTML sidebar stuff is all generated internally right now as part of the taskless.io site. I'll dig into that today & tomorrow since the layout changes would also impact the other things like the taskless.io homepage.

**Comment by TAKANOME-DEV** [comment]
Oh I see, got it :+1:

**Comment by jakobo** [comment]
Alright, I've updated our sidebar with a few fixes:
- On mobile, a new Table of Contents button that allows us to hide the sidebar, increasing readability
- On non-mobile the sidebar now uses the sticky property with overflow settings which allows it to stay on page while scrolling through docs

These are now live on taskless.io/docs

If you have a PR for the typos, we'll gladly accept it. Thank you again for contributing! 🙇🏻‍♂️

**Comment by TAKANOME-DEV** [comment]
Awesome :fire:
